/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import dao.daonhanvien;
import entity.nhanvien;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Haru
 */
public class quanlynhanvien extends javax.swing.JFrame {

    DefaultTableModel tblModel = new DefaultTableModel();

    public quanlynhanvien() throws SQLException, ClassNotFoundException {
        initComponents();
        icon();
        LoadData2Table();
    }

    public void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/giaodien/covericon.png")));
    }

    public void LoadData2Table() throws SQLException, ClassNotFoundException {
        List<nhanvien> b = dao.daonhanvien.getALLNV();
        //--- Thêm các tiêu đề cho cột của bảng hiển thị
        tblModel = new DefaultTableModel();
        tblModel.addColumn("mã nhân viên");
        tblModel.addColumn("tên nhân viên");
        tblModel.addColumn("ngày sinh");
        tblModel.addColumn("giới tính");
        tblModel.addColumn("quê quán");
        tblModel.addColumn("số điện thoại");
        tblModel.addColumn("hệ số lương");
        //--- frmadd lần lượt các row
        for (nhanvien nhanvien1 : b) {
            Vector<String> row = new Vector<>();
            row.addElement(String.valueOf(nhanvien1.getManv()));
            row.addElement(nhanvien1.getTennv());
            row.addElement(String.valueOf(nhanvien1.getNgaysinh()));
            row.addElement(nhanvien1.getGioitinh());
            row.addElement(nhanvien1.getQuequan());
            row.addElement(nhanvien1.getSdt());
            row.addElement(String.valueOf(nhanvien1.getHesoluong()));
            tblModel.addRow(row);
        }
        jXTable1.setModel(tblModel);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        del = new javax.swing.JButton();
        reload = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        USER = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NhanVien");
        setBackground(new java.awt.Color(102, 255, 255));

        back.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Go Back_50px.png"))); // NOI18N
        back.setMaximumSize(new java.awt.Dimension(87, 25));
        back.setMinimumSize(new java.awt.Dimension(87, 25));
        back.setPreferredSize(new java.awt.Dimension(87, 25));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jXTable1.setEditable(false);
        jScrollPane2.setViewportView(jXTable1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Edit File_50px.png"))); // NOI18N
        update.setMaximumSize(new java.awt.Dimension(87, 25));
        update.setMinimumSize(new java.awt.Dimension(87, 25));
        update.setPreferredSize(new java.awt.Dimension(87, 25));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Plus_50px.png"))); // NOI18N
        add.setMaximumSize(new java.awt.Dimension(87, 25));
        add.setMinimumSize(new java.awt.Dimension(87, 25));
        add.setPreferredSize(new java.awt.Dimension(87, 25));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Trash_50px.png"))); // NOI18N
        del.setMaximumSize(new java.awt.Dimension(87, 25));
        del.setMinimumSize(new java.awt.Dimension(87, 25));
        del.setPreferredSize(new java.awt.Dimension(87, 25));
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        reload.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        reload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/refresh-flat.png"))); // NOI18N
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reload, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        insert.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Search_50px.png"))); // NOI18N
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insert)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        USER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        USER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Account_50px.png"))); // NOI18N
        USER.setText("user:");
        USER.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        frmmenu b = new frmmenu();
        b.getContentPane().setBackground(Color.white);
        b.USER.setText(USER.getText());
        b.pack();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        new frmadd().setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {

            DefaultTableModel dtm = (DefaultTableModel) jXTable1.getModel();
            int j = jXTable1.getSelectedRow();
            System.out.println(j);
            if (j != -1) {
                int i = jXTable1.convertRowIndexToModel(j);
                Date ns = new SimpleDateFormat("yyyy-MM-dd").parse((String) dtm.getValueAt(i, 2));
                frmupdatenv frmud = new frmupdatenv();
                frmud.setVisible(true);
                frmud.id.setText((String) dtm.getValueAt(i, 0));
                frmud.nem.setText((String) dtm.getValueAt(i, 1));
                frmud.date.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String) dtm.getValueAt(i, 2)));
                if ("nam".equals((String) dtm.getValueAt(i, 3))) {
                    frmud.nam.setSelected(true);
                } else {
                    frmud.nu.setSelected(true);
                }
                frmud.que.setText((String) dtm.getValueAt(i, 4));
                frmud.sdt.setText((String) dtm.getValueAt(i, 5));
                frmud.hsl.setText((String) dtm.getValueAt(i, 6));
            }

        } catch (SQLException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) jXTable1.getModel();
        nhanvien nv1 = new nhanvien();
        int j = jXTable1.getSelectedRow();
        int i = jXTable1.convertRowIndexToModel(j);

        if (j != -1) {
            try {
                nv1.setManv((String) dtm.getValueAt(i, 0));

                daonhanvien.DeleteNV(nv1);
                LoadData2Table();
            } catch (SQLException ex) {
                Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delActionPerformed

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        try {
            LoadData2Table();
            jTextField1.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        try {
            String manv = jTextField1.getText();
            List<nhanvien> b = daonhanvien.FindNV(manv);
            tblModel.setRowCount(0);

            for (nhanvien nhanvien1 : b) {
                Vector<String> row = new Vector<>();
                row.addElement(String.valueOf(nhanvien1.getManv()));
                row.addElement(nhanvien1.getTennv());
                row.addElement(String.valueOf(nhanvien1.getNgaysinh()));
                row.addElement(nhanvien1.getGioitinh());
                row.addElement(nhanvien1.getQuequan());
                row.addElement(nhanvien1.getSdt());
                row.addElement(String.valueOf(nhanvien1.getHesoluong()));
                tblModel.addRow(row);
            }
            jXTable1.setModel(tblModel);

        } catch (SQLException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new quanlynhanvien().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(quanlynhanvien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel USER;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JButton del;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXTable jXTable1;
    private javax.swing.JButton reload;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
