/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package giaodien;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Haru
 */
public class frmmenu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public frmmenu() {
        initComponents();
        icon();
    }

    public void icon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/giaodien/covericon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btQLNV = new javax.swing.JButton();
        btQLBH = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btQLTK = new javax.swing.JButton();
        btThongKe = new javax.swing.JButton();
        USER = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainMenu");
        setPreferredSize(new java.awt.Dimension(800, 600));

        btQLNV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Account_50px.png"))); // NOI18N
        btQLNV.setText("QUẢN LÝ NHÂN VIÊN");
        btQLNV.setMaximumSize(new java.awt.Dimension(270, 40));
        btQLNV.setMinimumSize(new java.awt.Dimension(270, 40));
        btQLNV.setPreferredSize(new java.awt.Dimension(270, 40));
        btQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLNVActionPerformed(evt);
            }
        });

        btQLBH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btQLBH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/icons8-ingredients-50.png"))); // NOI18N
        btQLBH.setText("QUẢN LÝ BÁN HÀNG");
        btQLBH.setMaximumSize(new java.awt.Dimension(270, 40));
        btQLBH.setMinimumSize(new java.awt.Dimension(270, 40));
        btQLBH.setPreferredSize(new java.awt.Dimension(270, 40));
        btQLBH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btQLBHMouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("ĐĂNG XUẤT");
        exit.setMaximumSize(new java.awt.Dimension(100, 40));
        exit.setMinimumSize(new java.awt.Dimension(100, 40));
        exit.setPreferredSize(new java.awt.Dimension(100, 40));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodien/images.png"))); // NOI18N

        btQLTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btQLTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Administrative Tools_50px.png"))); // NOI18N
        btQLTK.setText("QUẢN LÝ TÀI KHOẢN");
        btQLTK.setMaximumSize(new java.awt.Dimension(270, 40));
        btQLTK.setMinimumSize(new java.awt.Dimension(270, 40));
        btQLTK.setPreferredSize(new java.awt.Dimension(270, 40));
        btQLTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btQLTKMouseClicked(evt);
            }
        });

        btThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btThongKe.setText("THỐNG KÊ ");
        btThongKe.setMaximumSize(new java.awt.Dimension(270, 40));
        btThongKe.setMinimumSize(new java.awt.Dimension(270, 40));
        btThongKe.setPreferredSize(new java.awt.Dimension(270, 40));
        btThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btThongKeMouseClicked(evt);
            }
        });

        USER.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        USER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageicon/Account_50px.png"))); // NOI18N
        USER.setText("user:");
        USER.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btQLTK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(USER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btQLBH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btQLTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        frmlogin a = new frmlogin();
                    a.getContentPane().setBackground(Color.white);
                    a.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void btQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLNVActionPerformed
        try {
            quanlynhanvien b = new quanlynhanvien();
            b.getContentPane().setBackground(Color.white);
            b.USER.setText(USER.getText());
            b.pack();
            b.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btQLNVActionPerformed

    private void btQLTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLTKMouseClicked
        try {
            quanlyuser b = new quanlyuser();
            b.getContentPane().setBackground(Color.white);
            b.pack();
            b.USER.setText(USER.getText());
            b.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btQLTKMouseClicked

    private void btQLBHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQLBHMouseClicked
        try {
            quanlybanhang b = new quanlybanhang();
            b.getContentPane().setBackground(Color.white);
            b.USER.setText(USER.getText());
            b.pack();
            b.setVisible(true);
            this.dispose();  // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btQLBHMouseClicked

    private void btThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btThongKeMouseClicked
        // TODO add your handling code here:
        frmthongke b;
        try {
            b = new frmthongke();
            b.getContentPane().setBackground(Color.white);
            b.USER.setText(USER.getText());
            b.pack();
            b.setVisible(true);
        this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btThongKeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmmenu c = new frmmenu();
                c.getContentPane().setBackground(Color.white);
                c.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel USER;
    private javax.swing.JButton btQLBH;
    private javax.swing.JButton btQLNV;
    private javax.swing.JButton btQLTK;
    private javax.swing.JButton btThongKe;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
